# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_XtbRunnerWindow(object):
    def setupUi(self, XtbRunnerWindow):
        XtbRunnerWindow.setObjectName("XtbRunnerWindow")
        XtbRunnerWindow.resize(770, 550)
        self.centralwidget = QtWidgets.QWidget(XtbRunnerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.geom_label = QtWidgets.QLabel(self.centralwidget)
        self.geom_label.setObjectName("geom_label")
        self.horizontalLayout_3.addWidget(self.geom_label)
        self.geom_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.geom_lineedit.setReadOnly(True)
        self.geom_lineedit.setObjectName("geom_lineedit")
        self.horizontalLayout_3.addWidget(self.geom_lineedit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.charge_label = QtWidgets.QLabel(self.centralwidget)
        self.charge_label.setObjectName("charge_label")
        self.horizontalLayout.addWidget(self.charge_label)
        self.charge_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.charge_spinbox.setMinimum(-99)
        self.charge_spinbox.setObjectName("charge_spinbox")
        self.horizontalLayout.addWidget(self.charge_spinbox)
        self.uhf_label = QtWidgets.QLabel(self.centralwidget)
        self.uhf_label.setObjectName("uhf_label")
        self.horizontalLayout.addWidget(self.uhf_label)
        self.uhf_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.uhf_spinbox.setObjectName("uhf_spinbox")
        self.horizontalLayout.addWidget(self.uhf_spinbox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gfn_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.gfn_checkbox.setChecked(True)
        self.gfn_checkbox.setObjectName("gfn_checkbox")
        self.horizontalLayout_4.addWidget(self.gfn_checkbox)
        self.molden_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.molden_checkbox.setObjectName("molden_checkbox")
        self.horizontalLayout_4.addWidget(self.molden_checkbox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.text_edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_edit.setObjectName("text_edit")
        self.verticalLayout.addWidget(self.text_edit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.grad_button = QtWidgets.QPushButton(self.centralwidget)
        self.grad_button.setObjectName("grad_button")
        self.horizontalLayout_2.addWidget(self.grad_button)
        self.opt_button = QtWidgets.QPushButton(self.centralwidget)
        self.opt_button.setObjectName("opt_button")
        self.horizontalLayout_2.addWidget(self.opt_button)
        self.siman_button = QtWidgets.QPushButton(self.centralwidget)
        self.siman_button.setObjectName("siman_button")
        self.horizontalLayout_2.addWidget(self.siman_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.xtbline_label = QtWidgets.QLabel(self.centralwidget)
        self.xtbline_label.setObjectName("xtbline_label")
        self.horizontalLayout_5.addWidget(self.xtbline_label)
        self.xtbline_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.xtbline_lineedit.setReadOnly(True)
        self.xtbline_lineedit.setObjectName("xtbline_lineedit")
        self.horizontalLayout_5.addWidget(self.xtbline_lineedit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        XtbRunnerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(XtbRunnerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 26))
        self.menubar.setObjectName("menubar")
        XtbRunnerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(XtbRunnerWindow)
        self.statusbar.setObjectName("statusbar")
        XtbRunnerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(XtbRunnerWindow)
        QtCore.QMetaObject.connectSlotsByName(XtbRunnerWindow)

    def retranslateUi(self, XtbRunnerWindow):
        _translate = QtCore.QCoreApplication.translate
        XtbRunnerWindow.setWindowTitle(_translate("XtbRunnerWindow", "runxtb"))
        self.geom_label.setText(_translate("XtbRunnerWindow", "Geometry:"))
        self.charge_label.setText(_translate("XtbRunnerWindow", "Charge:"))
        self.uhf_label.setText(_translate("XtbRunnerWindow", "Unpaired electrons:"))
        self.gfn_checkbox.setText(_translate("XtbRunnerWindow", "gfn"))
        self.molden_checkbox.setText(_translate("XtbRunnerWindow", "molden"))
        self.grad_button.setText(_translate("XtbRunnerWindow", "Grad"))
        self.opt_button.setText(_translate("XtbRunnerWindow", "Opt"))
        self.siman_button.setText(_translate("XtbRunnerWindow", "Siman"))
        self.xtbline_label.setText(_translate("XtbRunnerWindow", "xtb line:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    XtbRunnerWindow = QtWidgets.QMainWindow()
    ui = Ui_XtbRunnerWindow()
    ui.setupUi(XtbRunnerWindow)
    XtbRunnerWindow.show()
    sys.exit(app.exec_())

